DEFAULT:                                                            
  mongo_url: mongodb://core@localhost:27017
  mongo_database: core4dev

logging:                                                            
  mongodb: INFO
  stderr: DEBUG
  stdout: ~

worker:
  min_free_ram: 32

api:
  setting:
    debug: True
    cookie_secret: hello world
  admin_password: hans
