#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'salt==3005.1','console_scripts','salt-call'
__requires__ = 'salt==3005.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('salt==3005.1', 'console_scripts', 'salt-call')()
    )
